In [21]:
!pip install numpy pandas scikit-learn matplotlib seaborn
!pip install torch transformers datasets gradio
!pip install nltk

Requirement already satisfied: numpy in /Users/varad/.pyenv/versions/3.11.9/envs/nlp_Fa/lib/python3.11/site-packages (2.4.3)
Requirement already satisfied: pandas in /Users/varad/.pyenv/versions/3.11.9/envs/nlp_Fa/lib/python3.11/site-packages (2.3.3)
Requirement already satisfied: scikit-learn in /Users/varad/.pyenv/versions/3.11.9/envs/nlp_Fa/lib/python3.11/site-packages (1.8.0)
Requirement already satisfied: matplotlib in /Users/varad/.pyenv/versions/3.11.9/envs/nlp_Fa/lib/python3.11/site-packages (3.10.8)
Requirement already satisfied: seaborn in /Users/varad/.pyenv/versions/3.11.9/envs/nlp_Fa/lib/python3.11/site-packages (0.13.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/varad/.pyenv/versions/3.11.9/envs/nlp_Fa/lib/python3.11/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /Users/varad/.pyenv/versions/3.11.9/envs/nlp_Fa/lib/python3.11/site-packages (from pandas) (2026.1.post1)
Requirement already satisfied: tzdata>=2022.7 in /Users/varad/.pyenv/versions/3.11.9/envs/nlp_Fa/lib/python3.11/site-packages (from pandas) (2025.3)
Requirement already satisfied: scipy>=1.10.0 in /Users/varad/.pyenv/versions/3.11.9/envs/nlp_Fa/lib/python3.11/site-packages (from scikit-learn) (1.17.1)
Requirement already satisfied: joblib>=1.3.0 in /Users/varad/.pyenv/versions/3.11.9/envs/nlp_Fa/lib/python3.11/site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in /Users/varad/.pyenv/versions/3.11.9/envs/nlp_Fa/lib/python3.11/site-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: contourpy>=1.0.1 in /Users/varad/.pyenv/versions/3.11.9/envs/nlp_Fa/lib/python3.11/site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /Users/varad/.pyenv/versions/3.11.9/envs/nlp_Fa/lib/python3.11/site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /Users/varad/.pyenv/versions/3.11.9/envs/nlp_Fa/lib/python3.11/site-packages (from matplotlib) (4.62.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /Users/varad/.pyenv/versions/3.11.9/envs/nlp_Fa/lib/python3.11/site-packages (from matplotlib) (1.5.0)
Requirement already satisfied: packaging>=20.0 in /Users/varad/.pyenv/versions/3.11.9/envs/nlp_Fa/lib/python3.11/site-packages (from matplotlib) (26.0)
Requirement already satisfied: pillow>=8 in /Users/varad/.pyenv/versions/3.11.9/envs/nlp_Fa/lib/python3.11/site-packages (from matplotlib) (12.1.1)
Requirement already satisfied: pyparsing>=3 in /Users/varad/.pyenv/versions/3.11.9/envs/nlp_Fa/lib/python3.11/site-packages (from matplotlib) (3.3.2)
Requirement already satisfied: six>=1.5 in /Users/varad/.pyenv/versions/3.11.9/envs/nlp_Fa/lib/python3.11/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 24.0 -> 26.0.1
[notice] To update, run: pip install --upgrade pip
Requirement already satisfied: torch in /Users/varad/.pyenv/versions/3.11.9/envs/nlp_Fa/lib/python3.11/site-packages (2.11.0)
Requirement already satisfied: transformers in /Users/varad/.pyenv/versions/3.11.9/envs/nlp_Fa/lib/python3.11/site-packages (5.4.0)
Requirement already satisfied: datasets in /Users/varad/.pyenv/versions/3.11.9/envs/nlp_Fa/lib/python3.11/site-packages (4.8.4)
Requirement already satisfied: gradio in /Users/varad/.pyenv/versions/3.11.9/envs/nlp_Fa/lib/python3.11/site-packages (6.10.0)
Requirement already satisfied: filelock in /Users/varad/.pyenv/versions/3.11.9/envs/nlp_Fa/lib/python3.11/site-packages (from torch) (3.25.2)
Requirement already satisfied: typing-extensions>=4.10.0 in /Users/varad/.pyenv/versions/3.11.9/envs/nlp_Fa/lib/python3.11/site-packages (from torch) (4.15.0)
Requirement already satisfied: setuptools<82 in /Users/varad/.pyenv/versions/3.11.9/envs/nlp_Fa/lib/python3.11/site-packages (from torch) (65.5.0)
Requirement already satisfied: sympy>=1.13.3 in /Users/varad/.pyenv/versions/3.11.9/envs/nlp_Fa/lib/python3.11/site-packages (from torch) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /Users/varad/.pyenv/versions/3.11.9/envs/nlp_Fa/lib/python3.11/site-packages (from torch) (3.6.1)
Requirement already satisfied: jinja2 in /Users/varad/.pyenv/versions/3.11.9/envs/nlp_Fa/lib/python3.11/site-packages (from torch) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /Users/varad/.pyenv/versions/3.11.9/envs/nlp_Fa/lib/python3.11/site-packages (from torch) (2026.2.0)
Requirement already satisfied: huggingface-hub<2.0,>=1.5.0 in /Users/varad/.pyenv/versions/3.11.9/envs/nlp_Fa/lib/python3.11/site-packages (from transformers) (1.8.0)
Requirement already satisfied: numpy>=1.17 in /Users/varad/.pyenv/versions/3.11.9/envs/nlp_Fa/lib/python3.11/site-packages (from transformers) (2.4.3)
Requirement already satisfied: packaging>=20.0 in /Users/varad/.pyenv/versions/3.11.9/envs/nlp_Fa/lib/python3.11/site-packages (from transformers) (26.0)
Requirement already satisfied: pyyaml>=5.1 in /Users/varad/.pyenv/versions/3.11.9/envs/nlp_Fa/lib/python3.11/site-packages (from transformers) (6.0.3)
Requirement already satisfied: regex>=2025.10.22 in /Users/varad/.pyenv/versions/3.11.9/envs/nlp_Fa/lib/python3.11/site-packages (from transformers) (2026.2.28)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /Users/varad/.pyenv/versions/3.11.9/envs/nlp_Fa/lib/python3.11/site-packages (from transformers) (0.22.2)
Requirement already satisfied: typer in /Users/varad/.pyenv/versions/3.11.9/envs/nlp_Fa/lib/python3.11/site-packages (from transformers) (0.24.1)
Requirement already satisfied: safetensors>=0.4.3 in /Users/varad/.pyenv/versions/3.11.9/envs/nlp_Fa/lib/python3.11/site-packages (from transformers) (0.7.0)
Requirement already satisfied: tqdm>=4.27 in /Users/varad/.pyenv/versions/3.11.9/envs/nlp_Fa/lib/python3.11/site-packages (from transformers) (4.67.3)
Requirement already satisfied: pyarrow>=21.0.0 in /Users/varad/.pyenv/versions/3.11.9/envs/nlp_Fa/lib/python3.11/site-packages (from datasets) (23.0.1)
Requirement already satisfied: dill<0.4.2,>=0.3.0 in /Users/varad/.pyenv/versions/3.11.9/envs/nlp_Fa/lib/python3.11/site-packages (from datasets) (0.4.1)
Requirement already satisfied: pandas in /Users/varad/.pyenv/versions/3.11.9/envs/nlp_Fa/lib/python3.11/site-packages (from datasets) (2.3.3)
Requirement already satisfied: requests>=2.32.2 in /Users/varad/.pyenv/versions/3.11.9/envs/nlp_Fa/lib/python3.11/site-packages (from datasets) (2.33.0)
Requirement already satisfied: httpx<1.0.0 in /Users/varad/.pyenv/versions/3.11.9/envs/nlp_Fa/lib/python3.11/site-packages (from datasets) (0.28.1)
Requirement already satisfied: xxhash in /Users/varad/.pyenv/versions/3.11.9/envs/nlp_Fa/lib/python3.11/site-packages (from datasets) (3.6.0)
Requirement already satisfied: multiprocess<0.70.20 in /Users/varad/.pyenv/versions/3.11.9/envs/nlp_Fa/lib/python3.11/site-packages (from datasets) (0.70.19)
Requirement already satisfied: aiofiles<25.0,>=22.0 in /Users/varad/.pyenv/versions/3.11.9/envs/nlp_Fa/lib/python3.11/site-packages (from gradio) (24.1.0)
Requirement already satisfied: anyio<5.0,>=3.0 in /Users/varad/.pyenv/versions/3.11.9/envs/nlp_Fa/lib/python3.11/site-packages (from gradio) (4.13.0)
Requirement already satisfied: brotli>=1.1.0 in /Users/varad/.pyenv/versions/3.11.9/envs/nlp_Fa/lib/python3.11/site-packages (from gradio) (1.2.0)
Requirement already satisfied: fastapi<1.0,>=0.115.2 in /Users/varad/.pyenv/versions/3.11.9/envs/nlp_Fa/lib/python3.11/site-packages (from gradio) (0.135.2)
Requirement already satisfied: ffmpy in /Users/varad/.pyenv/versions/3.11.9/envs/nlp_Fa/lib/python3.11/site-packages (from gradio) (1.0.0)
Requirement already satisfied: gradio-client==2.4.0 in /Users/varad/.pyenv/versions/3.11.9/envs/nlp_Fa/lib/python3.11/site-packages (from gradio) (2.4.0)
Requirement already satisfied: groovy~=0.1 in /Users/varad/.pyenv/versions/3.11.9/envs/nlp_Fa/lib/python3.11/site-packages (from gradio) (0.1.2)
Requirement already satisfied: hf-gradio<1.0,>=0.3.0 in /Users/varad/.pyenv/versions/3.11.9/envs/nlp_Fa/lib/python3.11/site-packages (from gradio) (0.3.0)
Requirement already satisfied: markupsafe<4.0,>=2.0 in /Users/varad/.pyenv/versions/3.11.9/envs/nlp_Fa/lib/python3.11/site-packages (from gradio) (3.0.3)
Requirement already satisfied: orjson~=3.0 in /Users/varad/.pyenv/versions/3.11.9/envs/nlp_Fa/lib/python3.11/site-packages (from gradio) (3.11.7)
Requirement already satisfied: pillow<13.0,>=8.0 in /Users/varad/.pyenv/versions/3.11.9/envs/nlp_Fa/lib/python3.11/site-packages (from gradio) (12.1.1)
Requirement already satisfied: pydantic<=3.0,>=2.0 in /Users/varad/.pyenv/versions/3.11.9/envs/nlp_Fa/lib/python3.11/site-packages (from gradio) (2.12.5)
Requirement already satisfied: pydub in /Users/varad/.pyenv/versions/3.11.9/envs/nlp_Fa/lib/python3.11/site-packages (from gradio) (0.25.1)
Requirement already satisfied: python-multipart>=0.0.18 in /Users/varad/.pyenv/versions/3.11.9/envs/nlp_Fa/lib/python3.11/site-packages (from gradio) (0.0.22)
Requirement already satisfied: pytz>=2017.2 in /Users/varad/.pyenv/versions/3.11.9/envs/nlp_Fa/lib/python3.11/site-packages (from gradio) (2026.1.post1)
Requirement already satisfied: safehttpx<0.2.0,>=0.1.7 in /Users/varad/.pyenv/versions/3.11.9/envs/nlp_Fa/lib/python3.11/site-packages (from gradio) (0.1.7)
Requirement already satisfied: semantic-version~=2.0 in /Users/varad/.pyenv/versions/3.11.9/envs/nlp_Fa/lib/python3.11/site-packages (from gradio) (2.10.0)
Requirement already satisfied: starlette<1.0,>=0.40.0 in /Users/varad/.pyenv/versions/3.11.9/envs/nlp_Fa/lib/python3.11/site-packages (from gradio) (0.52.1)
Requirement already satisfied: tomlkit<0.14.0,>=0.12.0 in /Users/varad/.pyenv/versions/3.11.9/envs/nlp_Fa/lib/python3.11/site-packages (from gradio) (0.13.3)
Requirement already satisfied: uvicorn>=0.14.0 in /Users/varad/.pyenv/versions/3.11.9/envs/nlp_Fa/lib/python3.11/site-packages (from gradio) (0.42.0)
Requirement already satisfied: idna>=2.8 in /Users/varad/.pyenv/versions/3.11.9/envs/nlp_Fa/lib/python3.11/site-packages (from anyio<5.0,>=3.0->gradio) (3.11)
Requirement already satisfied: typing-inspection>=0.4.2 in /Users/varad/.pyenv/versions/3.11.9/envs/nlp_Fa/lib/python3.11/site-packages (from fastapi<1.0,>=0.115.2->gradio) (0.4.2)
Requirement already satisfied: annotated-doc>=0.0.2 in /Users/varad/.pyenv/versions/3.11.9/envs/nlp_Fa/lib/python3.11/site-packages (from fastapi<1.0,>=0.115.2->gradio) (0.0.4)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /Users/varad/.pyenv/versions/3.11.9/envs/nlp_Fa/lib/python3.11/site-packages (from fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (3.13.4)
Requirement already satisfied: certifi in /Users/varad/.pyenv/versions/3.11.9/envs/nlp_Fa/lib/python3.11/site-packages (from httpx<1.0.0->datasets) (2026.2.25)
Requirement already satisfied: httpcore==1.* in /Users/varad/.pyenv/versions/3.11.9/envs/nlp_Fa/lib/python3.11/site-packages (from httpx<1.0.0->datasets) (1.0.9)
Requirement already satisfied: h11>=0.16 in /Users/varad/.pyenv/versions/3.11.9/envs/nlp_Fa/lib/python3.11/site-packages (from httpcore==1.*->httpx<1.0.0->datasets) (0.16.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.2 in /Users/varad/.pyenv/versions/3.11.9/envs/nlp_Fa/lib/python3.11/site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (1.4.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/varad/.pyenv/versions/3.11.9/envs/nlp_Fa/lib/python3.11/site-packages (from pandas->datasets) (2.9.0.post0)
Requirement already satisfied: tzdata>=2022.7 in /Users/varad/.pyenv/versions/3.11.9/envs/nlp_Fa/lib/python3.11/site-packages (from pandas->datasets) (2025.3)
Requirement already satisfied: annotated-types>=0.6.0 in /Users/varad/.pyenv/versions/3.11.9/envs/nlp_Fa/lib/python3.11/site-packages (from pydantic<=3.0,>=2.0->gradio) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.5 in /Users/varad/.pyenv/versions/3.11.9/envs/nlp_Fa/lib/python3.11/site-packages (from pydantic<=3.0,>=2.0->gradio) (2.41.5)
Requirement already satisfied: charset_normalizer<4,>=2 in /Users/varad/.pyenv/versions/3.11.9/envs/nlp_Fa/lib/python3.11/site-packages (from requests>=2.32.2->datasets) (3.4.6)
Requirement already satisfied: urllib3<3,>=1.26 in /Users/varad/.pyenv/versions/3.11.9/envs/nlp_Fa/lib/python3.11/site-packages (from requests>=2.32.2->datasets) (2.6.3)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /Users/varad/.pyenv/versions/3.11.9/envs/nlp_Fa/lib/python3.11/site-packages (from sympy>=1.13.3->torch) (1.3.0)
Requirement already satisfied: click>=8.2.1 in /Users/varad/.pyenv/versions/3.11.9/envs/nlp_Fa/lib/python3.11/site-packages (from typer->transformers) (8.3.1)
Requirement already satisfied: shellingham>=1.3.0 in /Users/varad/.pyenv/versions/3.11.9/envs/nlp_Fa/lib/python3.11/site-packages (from typer->transformers) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /Users/varad/.pyenv/versions/3.11.9/envs/nlp_Fa/lib/python3.11/site-packages (from typer->transformers) (14.3.3)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /Users/varad/.pyenv/versions/3.11.9/envs/nlp_Fa/lib/python3.11/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /Users/varad/.pyenv/versions/3.11.9/envs/nlp_Fa/lib/python3.11/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /Users/varad/.pyenv/versions/3.11.9/envs/nlp_Fa/lib/python3.11/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /Users/varad/.pyenv/versions/3.11.9/envs/nlp_Fa/lib/python3.11/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /Users/varad/.pyenv/versions/3.11.9/envs/nlp_Fa/lib/python3.11/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /Users/varad/.pyenv/versions/3.11.9/envs/nlp_Fa/lib/python3.11/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /Users/varad/.pyenv/versions/3.11.9/envs/nlp_Fa/lib/python3.11/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (1.23.0)
Requirement already satisfied: six>=1.5 in /Users/varad/.pyenv/versions/3.11.9/envs/nlp_Fa/lib/python3.11/site-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.17.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /Users/varad/.pyenv/versions/3.11.9/envs/nlp_Fa/lib/python3.11/site-packages (from rich>=12.3.0->typer->transformers) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /Users/varad/.pyenv/versions/3.11.9/envs/nlp_Fa/lib/python3.11/site-packages (from rich>=12.3.0->typer->transformers) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in /Users/varad/.pyenv/versions/3.11.9/envs/nlp_Fa/lib/python3.11/site-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->transformers) (0.1.2)

[notice] A new release of pip is available: 24.0 -> 26.0.1
[notice] To update, run: pip install --upgrade pip
Requirement already satisfied: nltk in /Users/varad/.pyenv/versions/3.11.9/envs/nlp_Fa/lib/python3.11/site-packages (3.9.4)
Requirement already satisfied: click in /Users/varad/.pyenv/versions/3.11.9/envs/nlp_Fa/lib/python3.11/site-packages (from nltk) (8.3.1)
Requirement already satisfied: joblib in /Users/varad/.pyenv/versions/3.11.9/envs/nlp_Fa/lib/python3.11/site-packages (from nltk) (1.5.3)
Requirement already satisfied: regex>=2021.8.3 in /Users/varad/.pyenv/versions/3.11.9/envs/nlp_Fa/lib/python3.11/site-packages (from nltk) (2026.2.28)
Requirement already satisfied: tqdm in /Users/varad/.pyenv/versions/3.11.9/envs/nlp_Fa/lib/python3.11/site-packages (from nltk) (4.67.3)

[notice] A new release of pip is available: 24.0 -> 26.0.1
[notice] To update, run: pip install --upgrade pip

In [22]:
import pandas as pd
import numpy as np
import re
import pickle
from collections import Counter
from sklearn.model_selection import train_test_split

In [23]:
print("hello")

hello

In [24]:
import re, math, pickle, os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from collections import Counter
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import DataLoader, TensorDataset, Dataset
from torch.optim import AdamW
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, f1_score, confusion_matrix
from transformers import AutoTokenizer, AutoModelForSequenceClassification, get_linear_schedule_with_warmup

In [25]:

import nltk

from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score
import torch
nltk.download('stopwords')
from nltk.corpus import stopwords

[nltk_data] Downloading package stopwords to /Users/varad/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [26]:
df = pd.read_csv("data/train-balanced-sarcasm.csv")
df = df.rename(columns={
    "comment": "text",
    "label": "label"
})

df = df[["text", "label"]]
df.dropna(inplace=True)

# Keep training interactive; full dataset is very large.
MAX_SAMPLES = 50000
if len(df) > MAX_SAMPLES:
    df = df.sample(n=MAX_SAMPLES, random_state=42).reset_index(drop=True)

print(f"Dataset rows used: {len(df)}")
df.head()

Dataset rows used: 50000

                                                text  label
0              Yes and the buff it desperately needs      1
1  Hilarious because i visited A2 one weekend las...      0
2         Have you asked them what they want to eat?      0
3  Because that worked out so well with the mater...      1
4   But white people can't be discriminated against!      1

In [27]:
stop_words = set(stopwords.words('english'))

def clean_text(text):
    text = text.lower()
    text = re.sub(r'http\S+', '', text)        
    text = re.sub(r'[^a-zA-Z\s]', '', text)    
    words = text.split()
    words = [w for w in words if w not in stop_words]
    return " ".join(words)

df['clean_text'] = df['text'].apply(clean_text)
df.head()

,text,label,clean_text
0,Yes and the buff it desperately needs,1,yes buff desperately needs
1,Hilarious because i visited A2 one weekend las...,0,hilarious visited one weekend last fall sat co...
2,Have you asked them what they want to eat?,0,asked want eat
3,Because that worked out so well with the mater...,1,worked well material guidelines google cannot ...
4,But white people can't be discriminated against!,1,white people cant discriminated

In [28]:
train_texts, val_texts, train_labels, val_labels = train_test_split(
    df['clean_text'],
    df['label'],
    test_size=0.1,
    random_state=42
)

In [29]:
from collections import Counter

def tokenize(text):
    return text.split()

all_tokens = []
for text in train_texts:
    all_tokens.extend(tokenize(text))

vocab = Counter(all_tokens)
vocab = {word: i+1 for i, (word, _) in enumerate(vocab.items())}

In [30]:
def encode(text, vocab):
    return [vocab.get(word, 0) for word in text.split()]

train_sequences = [encode(text, vocab) for text in train_texts]
val_sequences = [encode(text, vocab) for text in val_texts]

In [31]:
from torch.nn.utils.rnn import pad_sequence

MAX_LEN = 80  # Truncate long comments to speed up LSTM training.
train_sequences = [torch.tensor(seq[:MAX_LEN], dtype=torch.long) for seq in train_sequences]
val_sequences = [torch.tensor(seq[:MAX_LEN], dtype=torch.long) for seq in val_sequences]

train_padded = pad_sequence(train_sequences, batch_first=True)
val_padded = pad_sequence(val_sequences, batch_first=True)

print(f"train_padded shape: {train_padded.shape}")
print(f"val_padded shape: {val_padded.shape}")

train_padded shape: torch.Size([45000, 80])
val_padded shape: torch.Size([5000, 67])

In [32]:
class TextDataset(Dataset):
    def __init__(self, texts, labels):
        self.texts = texts
        self.labels = torch.tensor(labels.values)

    def __len__(self):
        return len(self.labels)

    def __getitem__(self, idx):
        return self.texts[idx], self.labels[idx]

In [33]:
train_dataset = TextDataset(train_padded, train_labels)
val_dataset = TextDataset(val_padded, val_labels)

train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)
val_loader = DataLoader(val_dataset, batch_size=32)

In [34]:
class LSTMModel(nn.Module):
    def __init__(self, vocab_size, embed_dim=128, hidden_dim=128):
        super().__init__()
        self.embedding = nn.Embedding(vocab_size+1, embed_dim)
        self.lstm = nn.LSTM(embed_dim, hidden_dim, batch_first=True)
        self.fc = nn.Linear(hidden_dim, 2)

    def forward(self, x):
        x = self.embedding(x)
        _, (hidden, _) = self.lstm(x)
        out = self.fc(hidden[-1])
        return out

In [35]:
if torch.backends.mps.is_available():
    device = torch.device("mps")
elif torch.cuda.is_available():
    device = torch.device("cuda")
else:
    device = torch.device("cpu")

print(f"Using device: {device}")

model = LSTMModel(len(vocab)).to(device)

criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters(), lr=0.001)

Using device: mps

In [36]:
EPOCHS = 3
LOG_EVERY = 100

for epoch in range(EPOCHS):
    model.train()
    total_loss = 0.0

    for batch_idx, (x, y) in enumerate(train_loader, start=1):
        x, y = x.to(device), y.to(device)

        optimizer.zero_grad()
        outputs = model(x)
        loss = criterion(outputs, y)
        loss.backward()
        optimizer.step()

        total_loss += loss.item()

        if batch_idx % LOG_EVERY == 0:
            avg_loss = total_loss / batch_idx
            print(f"Epoch {epoch+1}/{EPOCHS} | Batch {batch_idx}/{len(train_loader)} | Avg Loss: {avg_loss:.4f}")

    print(f"Epoch {epoch+1}/{EPOCHS} complete | Total Loss: {total_loss:.4f}")

Epoch 1/3 | Batch 100/1407 | Avg Loss: 0.6979
Epoch 1/3 | Batch 200/1407 | Avg Loss: 0.6955
Epoch 1/3 | Batch 300/1407 | Avg Loss: 0.6949
Epoch 1/3 | Batch 400/1407 | Avg Loss: 0.6945
Epoch 1/3 | Batch 500/1407 | Avg Loss: 0.6943
Epoch 1/3 | Batch 600/1407 | Avg Loss: 0.6942
Epoch 1/3 | Batch 700/1407 | Avg Loss: 0.6941
Epoch 1/3 | Batch 800/1407 | Avg Loss: 0.6940
Epoch 1/3 | Batch 900/1407 | Avg Loss: 0.6939
Epoch 1/3 | Batch 1000/1407 | Avg Loss: 0.6938
Epoch 1/3 | Batch 1100/1407 | Avg Loss: 0.6938
Epoch 1/3 | Batch 1200/1407 | Avg Loss: 0.6938
Epoch 1/3 | Batch 1300/1407 | Avg Loss: 0.6937
Epoch 1/3 | Batch 1400/1407 | Avg Loss: 0.6937
Epoch 1/3 complete | Total Loss: 976.0240
Epoch 2/3 | Batch 100/1407 | Avg Loss: 0.6933
Epoch 2/3 | Batch 200/1407 | Avg Loss: 0.6933
Epoch 2/3 | Batch 300/1407 | Avg Loss: 0.6931
Epoch 2/3 | Batch 400/1407 | Avg Loss: 0.6932
Epoch 2/3 | Batch 500/1407 | Avg Loss: 0.6932
Epoch 2/3 | Batch 600/1407 | Avg Loss: 0.6932
Epoch 2/3 | Batch 700/1407 | Avg Loss: 0.6932
Epoch 2/3 | Batch 800/1407 | Avg Loss: 0.6932
Epoch 2/3 | Batch 900/1407 | Avg Loss: 0.6932
Epoch 2/3 | Batch 1000/1407 | Avg Loss: 0.6932
Epoch 2/3 | Batch 1100/1407 | Avg Loss: 0.6932
Epoch 2/3 | Batch 1200/1407 | Avg Loss: 0.6932
Epoch 2/3 | Batch 1300/1407 | Avg Loss: 0.6932
Epoch 2/3 | Batch 1400/1407 | Avg Loss: 0.6932
Epoch 2/3 complete | Total Loss: 975.3493
Epoch 3/3 | Batch 100/1407 | Avg Loss: 0.6931
Epoch 3/3 | Batch 200/1407 | Avg Loss: 0.6932
Epoch 3/3 | Batch 300/1407 | Avg Loss: 0.6932
Epoch 3/3 | Batch 400/1407 | Avg Loss: 0.6932
Epoch 3/3 | Batch 500/1407 | Avg Loss: 0.6932
Epoch 3/3 | Batch 600/1407 | Avg Loss: 0.6932
Epoch 3/3 | Batch 700/1407 | Avg Loss: 0.6932
Epoch 3/3 | Batch 800/1407 | Avg Loss: 0.6932
Epoch 3/3 | Batch 900/1407 | Avg Loss: 0.6932
Epoch 3/3 | Batch 1000/1407 | Avg Loss: 0.6932
Epoch 3/3 | Batch 1100/1407 | Avg Loss: 0.6932
Epoch 3/3 | Batch 1200/1407 | Avg Loss: 0.6932
Epoch 3/3 | Batch 1300/1407 | Avg Loss: 0.6932
Epoch 3/3 | Batch 1400/1407 | Avg Loss: 0.6932
Epoch 3/3 complete | Total Loss: 975.3184